
# the python base image, onbuild copies the files and installs the needed dependancies.
FROM python:3-onbuild

# Specify which port the app is running on.
EXPOSE 5000

# command to run the application.
CMD ["python", "./app.py"]

